import Head from 'next/head'

import { Inter } from 'next/font/google'

import AboutPage from '@/components/templates/about'

const inter = Inter({ subsets: ['latin'] })

export default function About() {
  return (
    <>
      <Head>
        <title>Palette Pro | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AboutPage />
      </main>
    </>
  )
}
