import { DialogProvider } from "@/context/DialogContext";
import Head from "next/head";
import Contact from "../components/templates/contact";

export default function ContactPage() {
  return (
    <>
      <Head>
        <title>Palette Pro | Contact </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DialogProvider>
          <Contact />
        </DialogProvider>
      </main>
    </>
  );
}
