import { Tips } from "@/components";
import Head from "next/head";

export default function TipsScreen() {
  return (
    <>
      <Head>
        <title>Palette Pro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Tips />
      </main>
    </>
  );
}
